status:
	@for dir in $$(find $$(pwd) -type d -name '.git'); do \
		cd "$$(dirname "$$dir")"; \
		if [ -n $(git status --porcelain) ]; then \
			echo "$$(pwd)"; \
		fi; \
		cd - > /dev/null; \
	done

.PHONY: status
